const flexVariable = {
  center: 'center',
  left: 'left',
  right: 'right',
  top: 'top',
  bottom: 'bottom',
  relative: 'relative',
  absolute: 'absolute',
  row: 'row',
  column: 'column',
  columnReverse: 'column-reverse',
  wrap: 'wrap',
  noWrap: 'nowrap',
  uppercase: 'uppercase',
  capitalize: 'capitalize',
  spaceBetween: 'space-between',
  bold: 'bold',
  flexStart: 'flex-start',
  flexEnd: 'flex-end',
  spaceAround: 'space-around',
  transparent: 'transparent',
  normal: 'normal',
  auto: 'auto',
  underline: 'underline',
};

export {flexVariable};
